query GetOrder($getOrderId: String!) {
  getOrder(id: $getOrderId) {
    billingDate
    code
    customer {
      address
      city
      code
      id
      naming
      zipCode
    }
    dueDate
    id
    items {
      unitPrice
      product {
        id
        code
        label
      }
      id
      amount
    }
  }
}

query GetOrders {
  getOrders {
    code
    customer {
      id
      naming
      zipCode
      code
      city
      address
    }
    dueDate
    id
    items {
      unitPrice
      product {
        id
        label
        code
      }
      id
      amount
    }
    billingDate
  }
}

mutation CreateOrder($createOrderInput: CreateOrderInput!) {
  createOrder(createOrderInput: $createOrderInput) {
    code
    id
  }
}

mutation UpdateOrder(
  $updateOrderId: String!
  $updateOrderInput: UpdateOrderInput!
) {
  updateOrder(id: $updateOrderId, updateOrderInput: $updateOrderInput) {
    code
    id
  }
}

mutation RemoveOrder($removeOrderId: String!) {
  removeOrder(id: $removeOrderId) {
    code
    id
  }
}

mutation RemoveOrders($ids: [String!]!) {
  removeOrders(ids: $ids)
}
