query GetCustomer($getCustomerId: String!) {
  getCustomer(id: $getCustomerId) {
    address
    city
    createdAt
    code
    id
    naming
    updatedAt
    zipCode
  }
}

query GetCustomers {
  getCustomers {
    address
    city
    code
    createdAt
    id
    naming
    updatedAt
    zipCode
  }
}

mutation CreateCustomer($createCustomerInput: CreateCustomerInput!) {
  createCustomer(createCustomerInput: $createCustomerInput) {
    id
    naming
  }
}

mutation UpdateCustomer(
  $updateCustomerId: String!
  $updateCustomerInput: UpdateCustomerInput!
) {
  updateCustomer(
    id: $updateCustomerId
    updateCustomerInput: $updateCustomerInput
  ) {
    id
    naming
  }
}

mutation RemoveCustomer($removeCustomerId: String!) {
  removeCustomer(id: $removeCustomerId) {
    id
    naming
  }
}

mutation RemoveCustomers($ids: [String!]!) {
  removeCustomers(ids: $ids)
}
