query GetOrder(
  $getOrderId: String!
  $populateCustomer: Boolean!
  $populateItems: Boolean!
) {
  getOrder(id: $getOrderId) {
    billingDate
    code
    customer(populate: $populateCustomer) {
      id
      code
    }
    items(populate: $populateItems) {
      id
      product {
        id
        code
        label
      }
      amount
      unitPrice
    }
    dueDate
    id
  }
}

query GetOrders($populateItems: Boolean!, $populateCustomer: Boolean!) {
  getOrders {
    billingDate
    code
    dueDate
    id
    items(populate: $populateItems) {
      amount
      id
      product {
        id
        code
        label
      }
      unitPrice
    }
    customer(populate: $populateCustomer) {
      id
      code
    }
  }
}

mutation CreateOrder($createOrderInput: CreateOrderInput!) {
  createOrder(createOrderInput: $createOrderInput) {
    code
    id
  }
}

mutation UpdateOrder(
  $updateOrderId: String!
  $updateOrderInput: UpdateOrderInput!
) {
  updateOrder(id: $updateOrderId, updateOrderInput: $updateOrderInput) {
    code
    id
  }
}

mutation RemoveOrder($removeOrderId: String!) {
  removeOrder(id: $removeOrderId) {
    code
    id
  }
}

mutation RemoveOrders($ids: [String!]!) {
  removeOrders(ids: $ids)
}
